name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *" # runs every 5 minutes
  workflow_dispatch:      # allows manual trigger too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          echo "Pinging Render app..."
          curl -fsS https://oncograph-agent.onrender.com/healthz \
            || echo "Ping failed (app may be asleep or slow to start)"
